GET https://api.github.com/search/users?q=abram
Authorization: token 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

###
GET https://api.github.com/users/abramfernandoh
Authorization: token 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

###
GET https://api.github.com/users/abramfernandoh/repos
Authorization: token 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